Fix exception during GPX import on PostgreSQL database caused by incorrect float<->int conversion
Exception:
ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'lxml.objectify.IntElement'